#:schema node_modules/wrangler/config-schema.json
name = "ficus-web"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
upload_source_maps = true

[dev]
port = 8764
inspector_port = 9224

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[[routes]]
pattern = "ficus.anderapps.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "ficus-web"
database_id = "4d3a0816-9b7a-4cf0-b5a6-776f7b90e89b"
migrations_dir = "migrations"
migrations_table = "__drizzle_migrations"

[[durable_objects.bindings]]
name = "REFILLING_TOKEN_BUCKET"
class_name = "RefillingTokenBucket"
script_name = 'ficus-rate-limiter'

[[durable_objects.bindings]]
name = "EXPIRING_TOKEN_BUCKET"
class_name = "ExpiringTokenBucket"
script_name = 'ficus-rate-limiter'

[[durable_objects.bindings]]
name = "THROTTLER"
class_name = "Throttler"
script_name = 'ficus-rate-limiter'

[[services]]
binding = "ARGON2"
service = "ficus-argon2"

[[services]]
binding = "NOTES"
service = "ficus-service-notes"

[[services]]
binding = "MARKDOWN"
service = "ficus-service-markdown"
