#:schema node_modules/wrangler/config-schema.json
name = "ficus-web"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[dev]
port = 8764
inspector_port = 9224

[[d1_databases]]
binding = "DB"
database_name = "ficus-web"
database_id = "4d3a0816-9b7a-4cf0-b5a6-776f7b90e89b"
migrations_dir = "migrations"
migrations_table = "__drizzle_migrations"

[[durable_objects.bindings]]
name = "REFILLING_TOKEN_BUCKET"
class_name = "RefillingTokenBucket"
script_name = 'ficus-rate-limiter'

[[durable_objects.bindings]]
name = "EXPIRING_TOKEN_BUCKET"
class_name = "ExpiringTokenBucket"
script_name = 'ficus-rate-limiter'

[[durable_objects.bindings]]
name = "THROTTLER"
class_name = "Throttler"
script_name = 'ficus-rate-limiter'

[[services]]
binding = "ARGON2"
service = "ficus-argon2"

[[services]]
binding = "NOTES"
service = "ficus-service-notes"
entrypoint = "NotesEntrypoint"

[[services]]
binding = "ATTACHMENTS"
service = "ficus-service-notes"
entrypoint = "AttachmentsEntrypoint"

[[services]]
binding = "FOLDERS"
service = "ficus-service-notes"
entrypoint = "FoldersEntrypoint"

[[services]]
binding = "TAGS"
service = "ficus-service-notes"
entrypoint = "TagsEntrypoint"
# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides
######## PREVIEW environment config ########
# [env.preview.vars]
# API_KEY = "xyz789"
# [[env.preview.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PREVIEW_NAMESPACE_ID>"
######## PRODUCTION environment config ########
# [env.production.vars]
# API_KEY = "abc123"
# [[env.production.kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "<PRODUCTION_NAMESPACE_ID>"
