packages:
  - libs/**
  - packages/**
  - apps/**
  - services/**
catalog:
  '@chromatic-com/storybook': ^3.2.3
  '@cloudflare/vitest-pool-workers': ^0.5.41
  '@cloudflare/workers-types': ^4.20250214.0
  '@dword-design/eslint-plugin-import-alias': ^5.1.1
  '@eslint/compat': ^1.2.6
  '@eslint/js': ^9.20.0
  '@hono/hono': npm:@jsr/hono__hono@^4.7.1
  '@iconify/svelte': ^4.2.0
  '@libsql/client': ^0.14.0
  '@nick/clsx': npm:@jsr/nick__clsx@^0.3.1
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  '@oslojs/otp': ^1.1.0
  '@playwright/test': ^1.50.1
  '@storybook/addon-essentials': ^8.4.7
  '@storybook/addon-interactions': ^8.4.7
  '@storybook/addon-svelte-csf': ^5.0.0-next.21
  '@storybook/blocks': ^8.4.7
  '@storybook/svelte': ^8.4.7
  '@storybook/sveltekit': ^8.4.7
  '@storybook/test': ^8.4.7
  '@sveltejs/adapter-cloudflare': ^5.0.1
  '@sveltejs/kit': ^2.16.1
  '@sveltejs/vite-plugin-svelte': ^5.0.0
  '@tailwindcss/container-queries': ^0.1.1
  '@tailwindcss/forms': ^0.5.10
  '@types/node': ^22.13.5
  '@typescript-eslint/utils': ^8.24.0
  arctic: ^3.3.0
  autoprefixer: ^10.4.20
  bits-ui: 1.0.0-next.90
  drizzle-kit: ^0.30.4
  drizzle-orm: ^0.39.3
  eslint: ^9.20.1
  eslint-config-prettier: ^9.1.0
  eslint-import-resolver-typescript: ^3.8.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-perfectionist: ^4.9.0
  eslint-plugin-svelte: ^2.36.0
  globals: ^15.15.0
  husky: ^9.1.7
  lint-staged: ^15.4.3
  ofetch: ^1.4.1
  prettier: ^3.5.1
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.11
  sort-package-json: ^2.14.0
  svelte: ^5.20.0
  svelte-check: ^4.1.4
  tailwind-merge: ^2.5.5
  tailwind-variants: ^0.3.1
  tailwindcss: ^3.4.9
  tailwindcss-animate: ^1.0.7
  tslib: ^2.3.0
  tsx: ^4.19.2
  typescript: ^5.7.3
  typescript-eslint: ^8.24.0
  uqr: ^0.1.2
  vite: ^6.1.0
  wrangler: v4-rc
