packages:
  - libs/**
  - packages/**
  - '!packages/**/build/**'
  - apps/**
  - services/**
catalog:
  '@cloudflare/vitest-pool-workers': ^0.7.5
  '@cloudflare/workers-types': ^4.20250321.0
  '@dword-design/eslint-plugin-import-alias': ^5.1.1
  '@eslint/compat': ^1.2.6
  '@eslint/js': ^9.20.0
  '@hono/zod-validator': ^0.4.3
  '@libsql/client': ^0.14.0
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0
  '@oslojs/otp': ^1.1.0
  '@playwright/test': ^1.50.1
  '@sentry/cli': ^2.42.4
  '@sentry/cloudflare': 9.12.0
  '@sentry/sveltekit': 9.12.0
  '@shikijs/engine-oniguruma': ^3.2.1
  '@shikijs/langs': ^3.2.1
  '@shikijs/rehype': ^3.2.1
  '@shikijs/themes': ^3.2.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/node': ^22.13.5
  '@typescript-eslint/utils': ^8.24.0
  arctic: ^3.3.0
  autoprefixer: ^10.4.20
  drizzle-kit: 0.30.5
  drizzle-orm: 0.41.0
  drizzle-zod: 0.7.0
  eslint: ^9.20.1
  eslint-config-prettier: ^9.1.0
  eslint-import-resolver-typescript: ^3.8.0
  eslint-plugin-drizzle: ^0.2.3
  eslint-plugin-import-x: ^4.6.1
  eslint-plugin-perfectionist: ^4.9.0
  eslint-plugin-svelte: ^2.36.0
  globals: ^15.15.0
  hono: ^4.7.4
  husky: ^9.1.7
  lint-staged: ^15.4.3
  ofetch: ^1.4.1
  prettier: ^3.5.1
  prettier-plugin-svelte: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.11
  rehype-sanitize: ^6.0.0
  rehype-stringify: ^10.0.1
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.1
  shiki: ^3.2.1
  sort-package-json: ^2.14.0
  toml: ^3.0.0
  tslib: ^2.3.0
  tsx: ^4.19.2
  typescript: ^5.7.3
  typescript-eslint: ^8.24.0
  unified: ^11.0.5
  unist-util-visit: ^5.0.0
  uqr: ^0.1.2
  vite: ^6.2.6
  wrangler: 4.7.2
  zod: ^3.24.2
