#:schema node_modules/wrangler/config-schema.json
name = "ficus-service-attachments"
main = "src/index.ts"
compatibility_date = "2025-02-14"
workers_dev = false

[observability]
enabled = true

[dev]
port = 8765
inspector_port = 9225

[[d1_databases]]
binding = "DB"
database_name = "ficus-attachments"
database_id = "99fb1adc-8df8-4807-824e-d23b787e1047"

[[r2_buckets]]
binding = "R2"
bucket_name = "ficus-attachments"
preview_bucket_name = "ficus-attachments-dev"
