// Generated by Wrangler by running `wrangler types`

interface Env {
	REFILLING_TOKEN_BUCKET: DurableObjectNamespace<
		import('@ficus/rate-limiter/src/index').RefillingTokenBucket
	>;
	EXPIRING_TOKEN_BUCKET: DurableObjectNamespace<
		import('@ficus/rate-limiter/src/index').ExpiringTokenBucket
	>;
	THROTTLER: DurableObjectNamespace<import('@ficus/rate-limiter/src/index').Throttler>;
	DB: D1Database;
	ARGON2: Fetcher;
	NOTES: Service<import('@ficus/service-notes/src/index').NotesEntrypoint>;
	ATTACHMENTS: Service<import('@ficus/service-notes/src/index').AttachmentsEntrypoint>;
	FOLDERS: Service<import('@ficus/service-notes/src/index').FoldersEntrypoint>;
	TAGS: Service<import('@ficus/service-notes/src/index').TagsEntrypoint>;
	R2: R2Bucket;
}
