// Generated by Wrangler by running `wrangler types`

interface Env {
	REFILLING_TOKEN_BUCKET: DurableObjectNamespace<
		import('@ficus/rate-limiter/src/index').RefillingTokenBucket
	>;
	EXPIRING_TOKEN_BUCKET: DurableObjectNamespace<
		import('@ficus/rate-limiter/src/index').ExpiringTokenBucket
	>;
	THROTTLER: DurableObjectNamespace<import('@ficus/rate-limiter/src/index').Throttler>;
	DB: D1Database;
	ARGON2: Fetcher;
	SERVICE_ATTACHMENTS: Fetcher;
}
