// Generated by Wrangler by running `wrangler types` (hash: 6202669a4eb51011f1f63013d994bfee)
// Runtime types generated with workerd@1.20250320.0 2025-02-14 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		R2: R2Bucket;
		DB: D1Database;
	}
}
type Env = Cloudflare.Env;
