// Generated by Wrangler by running `wrangler types`

interface Env {
  REFILL_RATE: 2;
  CAPACITY: 10;
  UPDATE_INTERVAL_MS: 1000;
  REFILLING_TOKEN_BUCKET: DurableObjectNamespace<
    import('./src/index').RefillingTokenBucket
  >;
}
