// Generated by Wrangler by running `wrangler types`

interface Env {
	REFILL_RATE: 2;
	CAPACITY: 10;
	UPDATE_INTERVAL_MS: 1000;
	RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
}
