name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      CF_D1_TOKEN: ${{ secrets.CF_D1_TOKEN }}
      CF_D1_DB_ID: ${{ secrets.CF_D1_DB_ID }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      # secrets can't start with GITHUB_ so we need to rename them
      GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}
    steps:
      # on main -> current + prev commit
      # pr -> pr commits + base commit
      - name: Determine fetch depth
        id: fetch-depth
        run: |
          echo "depth=$(( ${{ github.event.pull_request.commits || 1 }} + 1 ))" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: ${{ steps.fetch-depth.outputs.depth  }}

      - name: Cache Turbo setup
        uses: actions/cache@v4
        with:
          path: '**/.turbo'
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      # SKIPPING because importing types from other packages is throwing errors
      # - name: Check
      #   run: pnpm run check

      - name: Build
        run: pnpm run ci:build

      - name: Lint
        run: pnpm run ci:lint

      - name: Test
        run: pnpm run ci:test
